apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-exporter
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - name: nginx-exporter
    protocol: TCP
    port: 9113
    targetPort: 9113