apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-exporter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx/nginx-prometheus-exporter:0.9.0
        name: nginx-prometheus-exporter
        args:
          - -nginx.scrape-uri=http://nginx:80/basic_status
        resources: {}
        ports:
          - containerPort: 9113