expose:
  tls:
    certSource: secret
    secret:
      secretName: "harbor.35.228.157.95.nip.io"

  ingress:
    hosts:
      core: core.harbor.35.228.157.95.nip.io
    annotations:
      kubernetes.io/ingress.class: "nginx"
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      cert-manager.io/acme-challenge-type: http01

externalURL: https://core.harbor.35.228.157.95.nip.io

notary:
  enabled: false