backend:
  type: es
  es:
    host: elasticsearch-master
tolerations:
  - operator: "Exists"

input:
  tail:
    parsers: nginx-ingress

parsers:
  enabled: true

  json:
  - name: nginx-ingress
    extraEntries: |
        Match   *
        Time_Format %d/%b/%Y:%H:%M:%S %z
        Time_Keep   On
        Remove  time
        Rename  @timestamp timestamp
        Rename  time_local timestamp
rawConfig: |
  @INCLUDE fluent-bit-service.conf
  @INCLUDE fluent-bit-input.conf
  @INCLUDE fluent-bit-filter.conf
  @INCLUDE fluent-bit-output.conf
  [FILTER]
    Name    modify
    Match   *
    Remove  time
    Remove  @timestamp