apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: web
spec:
  containers:
  - image: vyzhiga/otuslab2-httpd:202104041817
    name: web
    resources: {}
    volumeMounts:
      - mountPath: /app
        name: app
  initContainers:
    - name: initlab2
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - mountPath: /app
          name: app
  volumes:
    - name: app
      emptyDir: {}